### ISSUE TITLE
Add support for RSA-3072 keys

### ISSUE THREAD

**Issue by crysknife** [Nitrokey/opcard-rs#118]
Unfortunately it seems this key size isn't yet supported. Can this be added as well or is there a technical limitation?

**Comment by sosthene-nitrokey** [comment]
This is a current implementation detail that will be lifted in the future. https://github.com/Nitrokey/opcard-rs/pull/116 implements it.

**Comment by sosthene-nitrokey** [comment]
This feature is available in the opcard release [v0.4.0](https://github.com/Nitrokey/opcard-rs/releases/tag/v0.4.0), which is included in the nitrokey 3 firmware test release [v1.3.1-test.20230417](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.3.1-test.20230417)
