### ISSUE TITLE
Error code for cryptographic operations with invalid key references

### ISSUE THREAD

**Issue by ebourg** [Nitrokey/opcard-rs#205]
Calling COMPUTE DIGITAL SIGNATURE or INTERNAL AUTHENTICATE when the referenced key doesn't exist returns an error code 6500 "No information given". Would it be possible to return a more precise error code, like 6A88 "Referenced data not found" for example?

**Comment by sosthene-nitrokey** [comment]
Thank you for the report.

This is not a path that normally happens since most tools will first check the state and detect that no key is present.
A fix is on the way.

**Comment by ebourg** [comment]
Thank you. I tried to retrieve the key information first to check if it can be used, but it added 300 ms of latency.
