### ISSUE TITLE
vpicc smartcard example crashes with "failed to fill whole buffer"

### ISSUE THREAD

**Issue by teythoon** [Nitrokey/opcard-rs#211]
After a short while running the sample virtual smartcard I see it crash like this:

```
% RUST_BACKTRACE=1 target/debug/examples/vpicc 
thread 'main' panicked at examples/vpicc.rs:37:14:
failed to run vpicc smartcard: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.81.0/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.81.0/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /usr/src/rustc-1.81.0/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::expect
             at /usr/src/rustc-1.81.0/library/core/src/result.rs:1059:23
   4: vpicc::main::{{closure}}
             at ./examples/vpicc.rs:35:9
   5: trussed::virt::Platform<S>::run_client_with_backends
             at /home/teythoon/.cargo/git/checkouts/trussed-34d232ec9a779a47/540ad72/src/virt.rs:151:9
   6: opcard::virt::with_client::{{closure}}
             at ./src/virt.rs:232:9
   7: trussed::virt::with_platform
             at /home/teythoon/.cargo/git/checkouts/trussed-34d232ec9a779a47/540ad72/src/virt.rs:54:5
   8: opcard::virt::with_client
             at ./src/virt.rs:231:5
   9: opcard::virt::with_ram_client
             at ./src/virt.rs:257:5
  10: vpicc::main
             at ./examples/vpicc.rs:31:5
  11: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.81.0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by robin-nitrokey** [comment]
Hm, I don’t think I’ve seen this before.  It looks like the error occurs in `vpicc::Connection::read` because there is not enough data to read from the TCP stream:

https://github.com/Nitrokey/vpicc-rs/blob/114d467f2549d8cbe1b34b840a30649a42ac16bf/src/lib.rs#L133-L141

Could there be some other process sending data to the vpicc port?

An easy fix could be to just return `Ok(())` instead of passing through the error if the `read` call fails here:

https://github.com/Nitrokey/vpicc-rs/blob/114d467f2549d8cbe1b34b840a30649a42ac16bf/src/lib.rs#L109

**Comment by teythoon** [comment]
> Hm, I don’t think I’ve seen this before. It looks like the error occurs in vpicc::Connection::read because there is not enough data to read from the TCP stream:

I have noticed that whenever I saw that panic, `pcscd` had died, so the panic seems to be just a symptom of the server going away.  I don't see anything in `pcscd`'s logs, except for the following:

```
00711743 [140737186367168] ../src/ifdwrapper.c:482:IFDControl() Card not transacted: 606
```

I tried to start `pcscd` with `gdb` to maybe see it crash, but I haven't been able to reproduce the problem while debugging `pcscd`, not sure why.  Do you have any advice on how to debug `pcscd`?

> Could there be some other process sending data to the vpicc port?

I don't believe so.  I ran tcpdump, and I think I only saw the traffic to and from the vpicc example.

**Comment by teythoon** [comment]
I believe I have found the problem: systemd decided that the service is inactive and "deactivated" it:

```
Oct 16 17:29:36 europ systemd[1]: Started pcscd.service - PC/SC Smart Card Daemon.
Oct 16 17:29:36 europ (pcscd)[1522302]: pcscd.service: Referenced but unset environment variable evaluates to an empty string: PCSCD_ARGS
Oct 16 17:30:37 europ systemd[1]: pcscd.service: Deactivated successfully.
```

So while I was experimenting, and fixing my code, systemd would kill pcscd, which would cause the virtual smart card to exit as well.  Explains why I haven't seen this when running pcscd manually.  Sorry for the noise.
