### ISSUE TITLE
FIDO2 functionality broken with opcard firmware

### ISSUE THREAD

**Issue by runcom** [Nitrokey/opcard-rs#91]
xref https://github.com/Nitrokey/nitrokey-3-firmware/issues/94

if you install the opcard firmware on a brand new nk3am, the fido2 functionality breaks in the same thread as explained in https://github.com/Nitrokey/nitrokey-3-firmware/issues/94#issuecomment-1286819682 where you can also find a reproducer

Notice only that flow is broken - meaning when make_cred + assert are run in the same process/thread - things like enrolling the token for linux pam still works just fine

**Comment by robin-nitrokey** [comment]
Thanks for the report!  As this is most likely not an issue with opcard directly but with its integration into the firmware, let’s continue the discussion in https://github.com/Nitrokey/nitrokey-3-firmware/issues/94.
